substitutions:
  _REGION: us-west1
  _AR_REPO: trustarant
  _SERVICE: trustarant-web
  _BACKEND_URL: https://trustarant-api-702422253553.us-west1.run.app

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/frontend:$SHORT_SHA
      - --build-arg
      - VITE_API_BASE_URL=${_BACKEND_URL}
      - ./frontend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/frontend:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE}
      - --region
      - ${_REGION}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/frontend:$SHORT_SHA

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/frontend:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
